import Footer from '@/components/Footer'
import Header from '@/components/Header'
import MainSection from '@/components/MainSection'

import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>CRUD app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <main className='h-[70vh]  overflow-y-scroll'>
          
        <MainSection />
     
      </main>
      <Footer />
    </>
  )
}
